apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: counter-cd-pipelinerun
spec:
  pipelineRef:
    name: counter-cd-pipeline
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: your-pvc-name
