apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
    - name: test
      image: python:3.9
      script: |
        pip install -r requirements.txt
        pip install nose
        nosetests -v --with-spec --spec-color
